apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tuxhs9d98-python 
  janus-idp.io/tekton: tuxhs9d98-python
  backstage.io/kubernetes-id: tuxhs9d98-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tuxhs9d98-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml