apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tuxhs9d98-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tuxhs9d98-python 
  name: tuxhs9d98-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tuxhs9d98-python 
